# Generated by Django 3.2.7 on 2021-09-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aricles',
            new_name='Articles',
        ),
    ]
